import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronDown,ChevronRight,ImagePlus,Layers3,LoaderCircle,LockKeyhole,Maximize2,Minimize2,Pause,Play,Plus,RefreshCw,ShoppingBag,Sparkles,Square,Upload,X,Network,FileText,AlertCircle,Mic,Search} from 'lucide-react';
import {api,money,type Room,type Health,type Preview,type Product} from './api';
import {useRoomStream} from './stream';
import {useVoiceInput,type VoiceTarget} from './voice';
import {FrameShop} from './FrameShop';
import {useRecordings,type RoomClip} from './recordings';
import {RecordingBar} from './RecordingBar';

const preferences=['Warm minimal','Mid-century','Natural textures','Quiet luxury'];
const sample='/images/sample-room.jpg';
function errorText(error:unknown){return error instanceof Error?error.message:'Something went wrong. Please try again.';}
function App(){
 const [room,setRoom]=useState<Room|null>(null);const roomRef=useRef<Room|null>(null);const [health,setHealth]=useState<Health|null>(null);const [budget,setBudget]=useState(2500);const [selectedPreferences,setSelectedPreferences]=useState(['Warm minimal','Natural textures']);const [keep,setKeep]=useState(['existing sofa','windows & layout']);const [keepInput,setKeepInput]=useState('');const [instruction,setInstruction]=useState('');
 const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [productsOpen,setProductsOpen]=useState(false);const [briefOpen,setBriefOpen]=useState(false);const [preview,setPreview]=useState<Preview|null>(null);const [original,setOriginal]=useState(false);const [connectionsOpen,setConnectionsOpen]=useState(false);const [documents,setDocuments]=useState<Record<string,unknown>[]|null>(null);const [workspaceError,setWorkspaceError]=useState('');const [saveResult,setSaveResult]=useState(false);const [samplePhoto,setSamplePhoto]=useState(true);
 const [productQuery,setProductQuery]=useState('');const [productSource,setProductSource]=useState<'amazon'|'catalog'>('amazon');
 const voice=useVoiceInput((text,target)=>{if(target==='products')setProductQuery(text);else setInstruction(value=>`${value}${value?' ':''}${text}`.slice(0,1600));setNotice(target==='products'?'Voice transcribed. Review your search, then find the pieces.':'Voice transcribed. Review your direction, then send.');});
 const [expanded,setExpanded]=useState(false);const nativeFullscreen=useRef(false);
 const taskEpoch=useRef(0);const fileInput=useRef<HTMLInputElement>(null);const stage=useRef<HTMLDivElement>(null);const stream=useRoomStream();
 const maximizeButton=useRef<HTMLButtonElement>(null);
 const roomImage=useRef<HTMLImageElement>(null),replayVideo=useRef<HTMLVideoElement>(null);const [replayClip,setReplayClip]=useState<RoomClip|null>(null),[replayUrl,setReplayUrl]=useState('');
 const recordings=useRecordings(room?.id,stream.video,stream.heldFrame,stream.held,stream.phase==='live',['live','pausing','paused','resuming'].includes(stream.phase));
 useEffect(()=>{if(!replayClip){setReplayUrl('');return;}const url=URL.createObjectURL(replayClip.blob);setReplayUrl(url);return()=>URL.revokeObjectURL(url);},[replayClip]);

 useEffect(()=>{
  const changed=()=>{if(document.fullscreenElement===stage.current){nativeFullscreen.current=true;setExpanded(true);}else if(nativeFullscreen.current){nativeFullscreen.current=false;setExpanded(false);maximizeButton.current?.focus();}};
  const keydown=(event:KeyboardEvent)=>{if(event.key==='Tab'&&stage.current?.classList.contains('is-expanded')){const controls=[...stage.current.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),a[href]')].filter(e=>e.getClientRects().length);const first=controls[0],last=controls.at(-1);if(event.shiftKey&&(document.activeElement===first||!stage.current.contains(document.activeElement))){event.preventDefault();last?.focus();}else if(!event.shiftKey&&(document.activeElement===last||!stage.current.contains(document.activeElement))){event.preventDefault();first?.focus();}}if(event.key==='Escape'&&!document.fullscreenElement&&stage.current?.classList.contains('is-expanded')){setExpanded(false);maximizeButton.current?.focus();}};
  document.addEventListener('fullscreenchange',changed);document.addEventListener('keydown',keydown);
  return()=>{document.removeEventListener('fullscreenchange',changed);document.removeEventListener('keydown',keydown);};
 },[]);
 useEffect(()=>{if(!expanded)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const size=()=>stage.current?.style.setProperty('--player-height',`${window.visualViewport?.height||window.innerHeight}px`);size();window.visualViewport?.addEventListener('resize',size);return()=>{document.body.style.overflow=previous;window.visualViewport?.removeEventListener('resize',size);stage.current?.style.removeProperty('--player-height');};},[expanded]);
 const toggleExpanded=async()=>{
  if(expanded){if(document.fullscreenElement===stage.current)await document.exitFullscreen();setExpanded(false);maximizeButton.current?.focus();return;}
  setExpanded(true);
  // Keep the same player/input mounted; unsupported fullscreen falls back to an expanded viewport.
  try{await stage.current?.requestFullscreen?.();}catch{/* The expanded viewport remains usable. */}
 };
 const endSession=()=>{taskEpoch.current++;setBusy('');void recordings.finish();void stream.stop();};
 const updateRoom=(value:Room)=>{setRoom(value);roomRef.current=value;localStorage.setItem('showroom.room',value.id);setSamplePhoto(!value.image_url||localStorage.getItem(`showroom.sample.${value.id}`)==='true');};
 useEffect(()=>{void api<Health>('/api/health').then(setHealth).catch(()=>setError('The design service is offline. Start the backend on port 8190, then retry.'));const id=localStorage.getItem('showroom.room');if(id)void api<Room>(`/api/rooms/${id}`).then(value=>{updateRoom(value);setBudget(value.budget);setSelectedPreferences(value.preferences);setKeep(value.keep);}).catch(()=>localStorage.removeItem('showroom.room'));},[]);
 const briefChanged=(value:Room)=>value.budget!==budget||JSON.stringify(value.preferences)!==JSON.stringify(selectedPreferences)||JSON.stringify(value.keep)!==JSON.stringify(keep);
 useEffect(()=>{if(!roomRef.current||!briefChanged(roomRef.current))return;const timer=setTimeout(()=>{if(!roomRef.current||!briefChanged(roomRef.current))return;void api<Room>(`/api/rooms/${roomRef.current!.id}`,{budget,preferences:selectedPreferences,keep},'PATCH').then(updateRoom).catch(error=>setError(errorText(error)));},450);return()=>clearTimeout(timer);},[budget,selectedPreferences,keep]);
 const ensureRoom=async()=>{let value=roomRef.current;if(!value){value=await api<Room>('/api/rooms',{name:'The living room',budget,preferences:selectedPreferences,keep});updateRoom(value);}else if(briefChanged(value)){value=await api<Room>(`/api/rooms/${value.id}`,{budget,preferences:selectedPreferences,keep},'PATCH');updateRoom(value);}return value;};
 const withTask=async(name:string,task:()=>Promise<void>)=>{const taskId=++taskEpoch.current;setBusy(name);setError('');setNotice('');try{await task();}catch(error){if(taskId===taskEpoch.current)setError(errorText(error));}finally{if(taskId===taskEpoch.current)setBusy('');}};
 const upload=async(file:File)=>{if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setError('Choose a JPG, PNG, or WebP room photograph.');return;}if(file.size>10*1024*1024){setError('Choose a photo smaller than 10 MB.');return;}await withTask('upload',async()=>{await stream.stop();const value=await ensureRoom();const form=new FormData();form.append('file',file);localStorage.setItem(`showroom.sample.${value.id}`,String(file.name==='sample-room.jpg'));updateRoom(await api<Room>(`/api/rooms/${value.id}/image`,form));setNotice('Your room photo is ready. Set your brief and start Orbis.');});};
 const start=()=>withTask('stream',async()=>{setReplayClip(null);let value=await ensureRoom();if(!value.image_url){const blob=await fetch(sample).then(response=>response.blob());const form=new FormData();form.append('file',new File([blob],'sample-room.jpg',{type:'image/jpeg'}));localStorage.setItem(`showroom.sample.${value.id}`,'true');value=await api<Room>(`/api/rooms/${value.id}/image`,form);updateRoom(value);}setOriginal(false);await stream.start(value);});
 const findProducts=()=>withTask('products',async()=>{const value=await ensureRoom();updateRoom(await api<Room>(`/api/rooms/${value.id}/recommendations`,{source:productSource,query:productQuery}));setProductsOpen(true);});
 const sendInstruction=async(event?:FormEvent)=>{event?.preventDefault();if(!instruction.trim())return;await withTask('steering',async()=>{const value=await ensureRoom();const result=await api<{room:Room;directive:{id:string;prompt:string}}>(`/api/rooms/${value.id}/directives`,{instruction:instruction.trim()});updateRoom(result.room);try{await stream.steer(result.directive.prompt);updateRoom(await api<Room>(`/api/rooms/${value.id}/directives/${result.directive.id}/ack`,{status:'accepted',message:'Orbis emitted prompt_accepted.'}));setInstruction('');setNotice(stream.phase==='paused'?'Direction accepted by Orbis. Resume when you’re ready to see the change.':'Direction accepted by Orbis. Watch the next moments of your room.');}catch(error){updateRoom(await api<Room>(`/api/rooms/${value.id}/directives/${result.directive.id}/ack`,{status:'failed',message:errorText(error)}));throw error;}});};
 const reviewSave=()=>withTask('preview',async()=>{const value=await ensureRoom();setPreview(await api<Preview>(`/api/rooms/${value.id}/export-preview`,{}));setSaveResult(false);setBriefOpen(true);});
 const approveSave=()=>withTask('export',async()=>{if(!room||!preview)return;const result=await api<{room:Room;exports:Room['exports']}>(`/api/rooms/${room.id}/export`,{approval_id:preview.approval_id,approved:true});updateRoom(result.room);setSaveResult(true);setNotice(result.exports.every(item=>item.verified===true)?'Your design brief and shopping list were saved and verified in Ambiguous.':'Ambiguous returned the saved document. Readback is not yet verified; open the link to check it.');});
 const readWorkspace=async()=>{setDocuments(null);setWorkspaceError('');setConnectionsOpen(true);try{const result=await api<unknown>('/api/ambiguous/documents');const records=Array.isArray(result)?result:(result as {documents?:Record<string,unknown>[]}).documents||[];setDocuments(records as Record<string,unknown>[]);}catch(error){setWorkspaceError(errorText(error));}};
 const active=['live','pausing','paused','resuming'].includes(stream.phase);const canDirect=!replayClip&&(stream.phase==='live'||stream.phase==='paused');const paused=stream.phase==='paused';const warming=stream.phase==='connecting'||stream.phase==='priming';const products=room?.products||[];const total=room?.total||0;const accepted=(room?.directives||[]).filter(item=>item.status==='accepted');const hasImage=Boolean(room?.image_url);const sourceImage=room?.image_url||sample;const sourceIsSample=samplePhoto;const displayedError=error||voice.error||stream.error;
 const voiceButton=(target:VoiceTarget)=><button type="button" className={`voice-button ${voice.state==='recording'&&voice.target===target?'recording':''}`} aria-label={voice.state==='recording'&&voice.target===target?`Stop recording ${target}`:`Record ${target} by voice`} title="Record with microphone · transcribed by OpenAI" disabled={Boolean(busy)||(voice.state!=='idle'&&!(voice.target===target&&voice.state==='recording'))} onClick={()=>voice.state==='recording'?voice.stop():void voice.start(target)}>{voice.state==='recording'&&voice.target===target?<Square size={17}/>:voice.target===target&&voice.state!=='idle'?<LoaderCircle className="spin" size={17}/>:<Mic size={18}/>}</button>;
 return <div className="app-shell">
  <header className="header"><a className="wordmark" href="/" aria-label="SHOWROOM home"><span className="logo-mark"><i/><i/><i/></span>SHOWROOM<span className="brand-period">®</span></a><div className="header-center"><span className="tiny-square"/> A little imagination. A room that’s yours.</div><button className="workspace-button" aria-label="My workspace" onClick={()=>void readWorkspace()}><span className="avatar">K</span><span>My workspace</span><ChevronDown size={14}/></button></header>
  <main>
   <div className="project-heading"><div><div className="breadcrumb">YOUR SPACES <ChevronRight size={11}/> ROOM 01</div><div className="title-line"><h1>The living room<span>.</span></h1><span className="draft-label">DESIGN STUDIO</span></div></div><div className="project-actions"><button className="quiet-button" onClick={()=>setConnectionsOpen(true)}><span className={`connection-dot ${health&&Object.values(health.integrations).every(item=>item.status==='connected')?'connected':''}`}/><span>{health?'Connections':'Connecting'}</span></button><button className="button dark save-top" aria-label="Save design brief" onClick={()=>void reviewSave()} disabled={Boolean(busy)}><span>Save design brief</span><ArrowUpRight size={16}/></button></div></div>
   <div className="studio-layout">
    <section className="room-workspace" aria-label="Room preview">
     <div className={`room-player ${expanded?'is-expanded':''}`} ref={stage} role={expanded?'dialog':undefined} aria-modal={expanded||undefined} aria-label={expanded?'Expanded room studio':undefined}>
     <div className={`room-stage ${replayClip?'is-replaying':''}`} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();const file=event.dataTransfer.files[0];if(file)void upload(file);}}>
      <img ref={roomImage} className="room-image" src={sourceImage} alt="A sunlit living room with a tan sofa, white lounge chairs, natural oak table and green plants"/>
      <video ref={stream.video} className={`room-video ${active&&!original?'visible':''}`} autoPlay playsInline muted onPlaying={stream.playing} aria-label="Live Orbis room redesign"/>
      <canvas ref={stream.heldFrame} className={`held-frame ${stream.held&&!original?'visible':''}`} aria-label="Held room frame"/>
      {replayClip&&<video ref={replayVideo} className="replay-video" src={replayUrl} controls controlsList="nofullscreen" playsInline aria-label="Recorded room replay"/>}
      <div className="room-shade"/>
      {!warming&&<FrameShop key={replayClip?.id||'current-room'} replaying={Boolean(replayClip)} ensureRoom={ensureRoom} getSource={()=>replayClip?replayVideo.current:!original&&stream.held?stream.heldFrame.current:!original&&active?stream.video.current:roomImage.current}/>}

      <div className="stage-top"><div className={`preview-label ${stream.phase==='live'?'is-live':''}`}><span className={warming?'pulse':''}/>{replayClip?'REPLAY · SAVED CLIP':original?'ORIGINAL PHOTO':paused?'PAUSED · ORBIS':stream.phase==='pausing'?'PAUSING · FRAME HELD':stream.phase==='resuming'?'RESUMING · ORBIS':active?'LIVE · ORBIS':warming?'ORBIS IS WARMING UP':hasImage&&!sourceIsSample?'YOUR ROOM PHOTO':'SAMPLE ROOM · REFERENCE'}</div><div className="stage-controls">{active&&!replayClip&&<button className="stage-action" aria-label={stream.phase==='resuming'&&stream.error?'Resume playback':paused?'Resume room':'Pause room'} disabled={Boolean(busy)||(!canDirect&&!(stream.phase==='resuming'&&stream.error))} onClick={()=>void withTask('playback',()=>stream.phase==='resuming'?stream.retryPlayback():paused?stream.resume():stream.pause())}>{!canDirect?<LoaderCircle className="spin" size={16}/>:paused?<Play size={16}/>:<Pause size={16}/>}<span>{paused?'Resume':stream.phase==='pausing'?'Pausing…':stream.phase==='resuming'?'Resuming…':'Pause'}</span></button>}<button ref={maximizeButton} className="stage-icon" aria-label={expanded?'Exit room fullscreen':'View room fullscreen'} aria-pressed={expanded} onClick={()=>void toggleExpanded()}>{expanded?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button></div></div>
      {warming&&<div className="warming-panel"><LoaderCircle className="spin" size={24}/><strong>Making room for your ideas.</strong><span>{stream.detail}</span><button onClick={()=>{taskEpoch.current++;setBusy('');void stream.stop();}}>Cancel session</button></div>}
      {!warming&&<div className="stage-bottom"><div><span className="eyebrow light">{active?'A NEW PERSPECTIVE':'START WITH WHAT’S YOURS'}</span><h2>{active?'Keep the room. Change the feeling.':'Your room, reconsidered.'}</h2><p>{active?'Direct the details as your space evolves.':'Keep what you love. Explore what comes next.'}</p></div><button className="upload-button" onClick={()=>fileInput.current?.click()} disabled={Boolean(busy)||active}><ImagePlus size={17}/><span>{hasImage?'Change photo':'Upload your room'}</span><ArrowUpRight size={15}/></button></div>}
      <input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" className="visually-hidden" aria-label="Upload room photo" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);event.target.value='';}}/>
     </div>
     <div className="preview-toolbar"><div className="preview-tabs"><button className={!original&&!replayClip?'selected':''} onClick={()=>{setOriginal(false);setReplayClip(null);}}><span className="tiny-square"/>{paused?'Paused room':active?'Live room':'Room photo'}</button><button className={original?'selected':''} onClick={()=>{setOriginal(true);setReplayClip(null);}} disabled={!active}>Original</button></div><span className="preview-disclosure">{replayClip?'Recorded Orbis video · drag the timeline to rewind':paused?'Frame held · resume to see your directions':active?'Illustrative preview · verify product fit below':sourceIsSample?'Sample reference · Unsplash':'Your uploaded photograph'}</span><button className="quiet-button fullscreen-session-button" onClick={()=>active?endSession():void start()} disabled={Boolean(busy)||warming}>{active?<Square size={13}/>:<Play size={13}/>}<span>{active?'End session':'Start Orbis'}</span></button><button className="quiet-button compact" onClick={()=>fileInput.current?.click()} disabled={Boolean(busy)||active}><Upload size={13}/><span>Replace</span></button></div>
     <RecordingBar recordings={recordings} clip={replayClip} onReplay={clip=>{setOriginal(false);setReplayClip(clip);}} onLive={()=>setReplayClip(null)} active={active} video={replayVideo}/>
     <form className={`composer ${active?'active':''}`} onSubmit={event=>void sendInstruction(event)}><Sparkles size={20}/><input aria-label="Live design direction" placeholder={replayClip?'Return to live to send a new direction':paused?'Describe the next change. Resume when ready.':active?'A warmer palette? A little more mid-century?':'Tell your room what comes next…'} value={instruction} onChange={event=>setInstruction(event.target.value)} maxLength={1600}/>{voiceButton('direction')}<span className="composer-state">{replayClip?'RETURN TO LIVE TO DIRECT':paused?'DIRECTION WHILE PAUSED':active?'LIVE DIRECTION':'START ORBIS TO DIRECT'}</span><button type="submit" aria-label="Send live direction" disabled={!canDirect||!instruction.trim()||Boolean(busy)}>{busy==='steering'?<LoaderCircle className="spin" size={19}/>:<ArrowRight size={20}/>}</button></form>
     {expanded&&<div className="fullscreen-feedback" role={displayedError?'alert':'status'}>{displayedError||voice.message||notice||(replayClip?'Replay mode · click a piece to shop, or return to the room.':paused?'Your frame stays here until you resume.':warming?stream.detail:'Type a direction and press Enter.')} {voice.state!=='idle'&&<button className="text-button" onClick={voice.cancel}>Cancel recording</button>} {stream.phase==='resuming'&&stream.error&&<button className="text-button" onClick={()=>void withTask('playback',stream.retryPlayback)}>Resume playback</button>}</div>}
     </div>
     <div className="suggestions"><span>TRY A DIRECTION</span>{['Make it warmer','Add a sculptural lamp','A touch of olive green'].map(text=><button key={text} onClick={()=>setInstruction(text)}>{text}<Plus size={11}/></button>)}</div>
     {accepted.length>0&&<div className="direction-history" aria-live="polite">{accepted.slice(-2).map((item,index)=><div key={item.id}><span className="direction-index">0{accepted.length- Math.min(accepted.length,2)+index+1}</span><span>{item.instruction}</span><span className="accepted"><Check size={12}/> Orbis accepted</span></div>)}</div>}
    </section>
    <aside className="brief-panel" aria-label="Design brief"><div className="section-kicker"><span>01 — THE BRIEF</span><Layers3 size={17}/></div><h2>A few things<br/>to make it yours.</h2><p className="panel-intro">Your taste. Your budget. Your non-negotiables.</p>
     <section className="budget-section"><label htmlFor="budget">The budget <span>USD</span></label><div className="budget-value"><span>$</span><input id="budget" type="number" min="50" max="100000" step="50" value={budget} onChange={event=>setBudget(Math.max(0,Number(event.target.value)))}/><span>furniture</span></div><input type="range" aria-label="Budget slider" min="250" max="10000" step="50" value={Math.min(10000,budget)} onChange={event=>setBudget(Number(event.target.value))} style={{'--range-progress':`${Math.max(0,(budget-250)/9750*100)}%`} as React.CSSProperties}/><div className="range-ends"><span>$250</span><span>$10,000</span></div></section>
     <section className="preference-section"><label>The feeling</label><div className="preference-options">{preferences.map(text=><button className={selectedPreferences.includes(text)?'chosen':''} key={text} onClick={()=>setSelectedPreferences(value=>value.includes(text)?value.filter(item=>item!==text):[...value,text])}>{text}{selectedPreferences.includes(text)?<Check size={12}/>:<Plus size={12}/>}</button>)}</div></section>
     <section className="keep-section"><label><LockKeyhole size={13}/> Keep in the room</label><div className="keep-list">{keep.map(text=><div key={text}><span className="keep-check"><Check size={10}/></span><span>{text}</span><button aria-label={`Remove keep constraint ${text}`} onClick={()=>setKeep(value=>value.filter(item=>item!==text))}><X size={12}/></button></div>)}</div><form className="add-keep" onSubmit={event=>{event.preventDefault();if(keepInput.trim()){setKeep(value=>[...new Set([...value,keepInput.trim()])]);setKeepInput('');}}}><Plus size={13}/><input aria-label="Add a keep constraint" placeholder="Something else to keep?" value={keepInput} onChange={event=>setKeepInput(event.target.value)} maxLength={100}/>{keepInput&&<button type="submit" aria-label="Add keep constraint"><Check size={13}/></button>}</form></section>
     <div className="brief-bottom">{active?<button className="button dark full" onClick={endSession}><Square size={13}/> End live session</button>:<button className="button dark full start-button" onClick={()=>void start()} disabled={Boolean(busy)||warming}>{warming||busy==='stream'?<LoaderCircle className="spin" size={16}/>:<Play size={14} fill="currentColor"/>}<span>{stream.phase==='error'||stream.phase==='disconnected'?'Retry Orbis':'Start Orbis'}</span><ArrowRight size={17}/></button>}<p><LockKeyhole size={11}/>{active?'Your brief stays with every direction.':'Your photo anchors the first live frame.'}</p></div>
    </aside>
   </div>
   {!expanded&&(displayedError||voice.message||notice)&&<div className={`feedback ${displayedError?'error':'success'}`} role={displayedError?'alert':'status'}>{displayedError?<AlertCircle size={17}/>:<Check size={17}/>}<span>{displayedError||voice.message||notice}</span>{voice.state!=='idle'&&<button className="text-button" onClick={voice.cancel}>Cancel recording</button>}<button aria-label="Dismiss message" onClick={()=>{setError('');setNotice('');voice.clearError();stream.clearError();}}><X size={15}/></button></div>}
   <section className={`shopping-section ${productsOpen?'is-open':''}`} aria-label="Sourced furniture"><div className="shopping-heading"><div className="shopping-title"><div className="section-kicker">02 — MAKE IT REAL</div><h2>A room you can bring home<span>.</span></h2><p>Real pieces. Sourced prices. A little less guesswork.</p></div><div className="shopping-actions">{products.length>0&&<div className="shopping-total"><span>{products.length} PIECES · {room?.unpriced_count?'PRICED SUBTOTAL':'SUBTOTAL'}</span><strong>{money(total)}</strong><small>{room?.unpriced_count?`${room.unpriced_count} price${room.unpriced_count===1?'':'s'} to check`:total<=budget?`${money(budget-total)} within budget`:`${money(total-budget)} over budget`}</small></div>}<button className="button outlined" onClick={()=>products.length?setProductsOpen(!productsOpen):void findProducts()} disabled={Boolean(busy)}>{busy==='products'?<LoaderCircle className="spin" size={16}/>:<ShoppingBag size={16}/>}<span>{products.length?(productsOpen?'Hide the pieces':'View the pieces'):'Find the pieces'}</span><ChevronDown className={productsOpen?'rotate':''} size={16}/></button></div></div>
    <form className="product-search" onSubmit={event=>{event.preventDefault();void findProducts();}}><div className="product-search-input"><Search size={18}/><input aria-label="Search furniture" placeholder="Search Amazon: a sculptural lamp, an olive armchair…" value={productQuery} onChange={event=>setProductQuery(event.target.value)} maxLength={1600}/>{voiceButton('products')}</div><select aria-label="Product source" value={productSource} onChange={event=>setProductSource(event.target.value as 'amazon'|'catalog')}><option value="amazon">Amazon · Exa search</option><option value="catalog">Curated IKEA catalog</option></select><button className="button dark" type="submit" disabled={Boolean(busy)||voice.state!=='idle'}>{busy==='products'?<LoaderCircle className="spin" size={16}/>:<Search size={16}/>}Search</button></form>
    <p className="search-note">{room?.product_source==='amazon'?'Amazon listings retrieved with Exa. Cached pages may be up to 6 hours old. Prices are source quotes, not checkout totals; unquoted items are excluded from the subtotal.':'Search Amazon through Exa using your brief, or select the curated IKEA catalog.'} Voice input is transcribed by OpenAI; review the text before searching.</p>
    {productsOpen&&<div className="shopping-content"><div className="product-list">{products.map((product,index)=><ProductRow product={product} index={index} key={product.id}/>)}</div><div className="sourcing-note"><div><Network size={18}/><div><strong>{room?.graph.status==='connected'||room?.graph.status==='neo4j'||room?.graph.status==='available'?'Connected to your room':'Why these pieces'}</strong><p>{room?.graph.explanation||'Recommendations respect your budget, style preferences, and the pieces you want to keep.'}</p><span className="graph-status">Graph: {room?.graph.status||'not queried'}</span></div></div><div className="source-footer"><span>{room?.product_source==='amazon'?'Amazon source quotes, before tax and shipping. Missing prices are excluded from the subtotal; verify on Amazon.':'Published catalog prices, before tax and shipping. Verify stock and dimensions with the retailer.'}</span><button className="text-button" onClick={()=>void findProducts()} disabled={Boolean(busy)}><RefreshCw size={12}/> Update for my brief</button></div></div></div>}
   </section>
   <footer><span>SHOWROOM <span className="footer-divider">/</span> YOUR SPACE, STILL YOURS.</span><span>Made for the way you want to live. <span className="footer-spark">✳</span></span></footer>
  </main>
  {briefOpen&&<div className="modal-backdrop" onClick={()=>!busy&&setBriefOpen(false)}><section className="modal brief-modal" role="dialog" aria-modal="true" aria-labelledby="save-title" onClick={event=>event.stopPropagation()}><div className="modal-top"><span className="section-kicker">03 — TAKE IT WITH YOU</span><button className="icon-button" aria-label="Close save review" onClick={()=>setBriefOpen(false)} disabled={Boolean(busy)}><X size={21}/></button></div><h2 id="save-title">{saveResult?'Consider it saved.':'One last look.'}</h2><p className="modal-description">{saveResult?(room?.exports.every(item=>item.verified===true)?'Your saved brief and shopping list were read back from Ambiguous.':'Ambiguous created your document. Readback has not yet been verified.'):'Review your design brief and shopping list before saving to Ambiguous.'}</p>{saveResult?<div className="export-links">{room?.exports.map((item,index)=><a key={String(item.id||index)} href={String(item.url||item.link||'#')} target="_blank" rel="noreferrer"><FileText size={18}/>{String(item.title||item.type||'Open saved document')}<ArrowUpRight size={17}/></a>)}</div>:<><div className="brief-summary"><div><span>THE ROOM</span><strong>{room?.name}</strong></div><div><span>THE BUDGET</span><strong>{money(budget)}</strong></div><div><span>THE PIECES</span><strong>{products.length} · {money(total)}</strong></div></div><div className="brief-preview"><h3>{preview?.title}</h3><pre>{preview?.content}</pre></div><p className="approval-note"><LockKeyhole size={14}/> This saves the brief and shopping list only. It does not purchase furniture.</p>{error&&<div className="feedback error" role="alert"><AlertCircle size={16}/>{error}</div>}<button className="button dark full" onClick={()=>void approveSave()} disabled={Boolean(busy)}>{busy==='export'?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>}Approve & save to Ambiguous<ArrowUpRight size={16}/></button></>}</section></div>}
  {connectionsOpen&&<div className="modal-backdrop" onClick={()=>setConnectionsOpen(false)}><section className="modal connections-modal" role="dialog" aria-modal="true" aria-labelledby="connections-title" onClick={event=>event.stopPropagation()}><div className="modal-top"><span className="section-kicker">YOUR WORKSPACE</span><button className="icon-button" aria-label="Close connections" onClick={()=>setConnectionsOpen(false)}><X size={21}/></button></div><h2 id="connections-title">The connections.</h2><p className="modal-description">The services behind your design studio.</p><div className="connection-list">{[['reactor','Orbis by Reactor','The live room'],['neo4j','Neo4j','Room relationships'],['ambiguous','Ambiguous','Your design documents'],['exa','Exa','Amazon product search'],['openai','OpenAI','Voice transcription']].map(([key,name,description])=><div key={key}><span className={`connection-dot ${health?.integrations[key]?.status==='connected'?'connected':''}`}/><div><strong>{name}</strong><small>{description}</small></div><span className="connection-status">{health?.integrations[key]?.status||'Checking'}</span></div>)}</div><button className="text-button" onClick={()=>void api<Health>('/api/health').then(setHealth).catch(error=>setWorkspaceError(errorText(error)))}><RefreshCw size={13}/> Refresh connections</button><div className="workspace-documents"><h3>Your Ambiguous documents</h3>{workspaceError?<p className="workspace-error">{workspaceError}</p>:documents===null?<button className="button outlined" onClick={()=>void readWorkspace()}><FileText size={15}/> Read workspace</button>:documents.length===0?<p>No documents returned by your workspace.</p>:documents.slice(0,6).map((document,index)=><a key={index} href={typeof document.url==='string'?document.url:typeof document.link==='string'?document.link:document.id?`https://app.ambiguous.ai/docs/${encodeURIComponent(String(document.id))}`:undefined} target="_blank" rel="noreferrer"><FileText size={15}/>{String(document.title||document.name||'Untitled document')}<ArrowUpRight size={14}/></a>)}</div></section></div>}
 </div>;
}
function ProductRow({product,index}:{product:Product;index:number}){const [imageFailed,setImageFailed]=useState(false);return <article className="product-row"><span className="product-number">0{index+1}</span><div className="product-image">{product.image_url&&!imageFailed&&(product.source!=='exa_amazon'||/^https:\/\/(?:m\.media-amazon\.com|images(?:-[a-z0-9]+)?\.ssl-images-amazon\.com)\/images\/I\//i.test(product.image_url))?<img src={product.image_url} alt={product.name} loading="lazy" referrerPolicy="no-referrer" onLoad={event=>{if(event.currentTarget.naturalWidth<10||event.currentTarget.naturalHeight<10)setImageFailed(true);}} onError={()=>setImageFailed(true)}/>:<ShoppingBag size={30} strokeWidth={1}/>}</div><div className="product-detail"><span className="product-brand">{product.brand||'SOURCED PIECE'} <span> / </span> {product.category}</span><h3>{product.name}</h3><p>{product.reason||product.rationale||'Selected to complement your room brief.'}</p>{product.dimensions&&<span className="dimensions">{typeof product.dimensions==='string'?product.dimensions:Object.entries(product.dimensions).map(([key,value])=>`${key}: ${value}`).join(' · ')}</span>}</div><div className="product-price"><strong>{product.price===null?'Check price':money(product.price)}</strong><a href={product.source_url} target="_blank" rel="noreferrer">{product.source_url.includes('amazon.com')?'View on Amazon':'View at retailer'}<ArrowUpRight size={13}/></a></div></article>;}
export default App;
