import {useEffect,useState,type RefObject} from 'react';
import {Download,LoaderCircle,Play,RotateCcw,Square,Video} from 'lucide-react';
import {clipTime,type RoomClip,useRecordings} from './recordings';
export function RecordingBar({recordings,clip,onReplay,onLive,active,video}:{recordings:ReturnType<typeof useRecordings>;clip:RoomClip|null;onReplay:(clip:RoomClip)=>void;onLive:()=>void;active:boolean;video:RefObject<HTMLVideoElement|null>}){
 const [url,setUrl]=useState(''),[time,setTime]=useState(0);
 useEffect(()=>{setTime(0);if(!clip){setUrl('');return;}const value=URL.createObjectURL(clip.blob);setUrl(value);return()=>URL.revokeObjectURL(value);},[clip]);
 useEffect(()=>{const player=video.current;if(!player)return;const changed=()=>setTime(player.currentTime);player.addEventListener('timeupdate',changed);return()=>player.removeEventListener('timeupdate',changed);},[clip]);
 const rewind=async()=>{const saved=await recordings.finish()||recordings.clips[0];if(saved)onReplay(saved);};
 return <div className="recording-bar"><div className="recording-actions">{recordings.recording?<><span className="recording-indicator"><i/>{clipTime(recordings.seconds)} REC</span><button onClick={()=>void rewind()}><Square size={13}/> Save & rewind</button></>:recordings.saving?<span role="status"><LoaderCircle className="spin" size={14}/> Saving clip…</span>:active&&!clip?<button onClick={recordings.start}><Video size={14}/> Record next clip</button>:null}{recordings.clips.length>0&&<><select aria-label="Saved room clips" value={clip?.id||''} onChange={event=>{const saved=recordings.clips.find(c=>c.id===event.target.value);if(saved)onReplay(saved);}}><option value="" disabled>Saved clips ({recordings.clips.length})</option>{recordings.clips.map((c,index)=><option key={c.id} value={c.id}>Clip {recordings.clips.length-index} · {clipTime(c.duration)} · {new Date(c.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</option>)}</select>{!clip&&<button onClick={()=>onReplay(recordings.clips[0])}><RotateCcw size={14}/> Replay</button>}</>}{clip&&<><button onClick={()=>{if(video.current)video.current.currentTime=Math.max(0,video.current.currentTime-10);}} aria-label="Rewind ten seconds"><RotateCcw size={14}/> 10s</button><a href={url} download={`showroom-${clip.createdAt.replaceAll(':','-')}.${clip.blob.type.includes('mp4')?'mp4':'webm'}`}><Download size={14}/> Download video</a><button onClick={onLive}><Play size={13}/>{active?'Return to live':'Return to room'}</button></>}</div>{clip?<><label className="replay-timeline"><span>{clipTime(time)}</span><input type="range" aria-label="Replay position" min="0" max={clip.duration} step="0.1" value={Math.min(time,clip.duration)} onChange={event=>{if(video.current){video.current.currentTime=Number(event.target.value);setTime(Number(event.target.value));}}}/><span>{clipTime(clip.duration)}</span></label><small>{clip.saved?'Saved in this browser':'Download to keep this clip'} · {active?'Orbis session remains active':'Recorded room video'} · use the timeline to rewind.</small></>:<small>{recordings.recording?'Recording the room locally. Save before closing this tab.':'New live sessions record automatically. Clips stay in this browser; download to keep a file.'}</small>}{recordings.error&&<p role="alert">{recordings.error}<button aria-label="Dismiss recording message" onClick={recordings.clearError}>×</button></p>}</div>;
}
